name: wechat_camera_picker
description: A camera picker which is an extension to wechat_assets_picker, but can be run separately.
version: 2.2.1
homepage: https://github.com/fluttercandies/flutter_wechat_camera_picker

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

publish_to: none

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.8.1
  device_info: ^2.0.0
  path: ^1.8.0
  path_provider: ^2.0.1
  # photo_manager: ^1.0.6
  # photo_manager: ^1.3.1
  photo_manager:
    git:
      url: "https://github.com/luowanglin/flutter_photo_manager.git"
      ref: "1.3.1.2"
  video_player: ^2.1.0
